## Latihan Data Cleaning : 21 Februari 2019

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('datahepatitis.csv')

In [3]:
data.shape

(155, 20)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
Class             155 non-null object
Age               155 non-null int64
Sex               155 non-null object
Steroid           154 non-null object
Antivirals        155 non-null object
Fatigue           154 non-null object
Malaise           154 non-null object
Anaroxia          154 non-null object
Liver Big         145 non-null object
Liver Firm        144 non-null object
Spleen Pabable    150 non-null object
Spiders           150 non-null object
Ascites           150 non-null object
Varices           150 non-null object
Bilirubin         149 non-null float64
Alk Phospat       126 non-null float64
SGOT              151 non-null float64
Albumin           139 non-null float64
Protime           88 non-null float64
Histology         155 non-null object
dtypes: float64(5), int64(1), object(14)
memory usage: 24.3+ KB

In [5]:
data.head(n=10)

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
0,die,30,female,no,yes,yes,yes,yes,no,yes,yes,yes,yes,yes,1.0,85.0,18.0,4.0,NaN,no
1,die,50,male,no,yes,no,yes,yes,no,yes,yes,yes,yes,yes,0.9,135.0,42.0,3.5,NaN,no
2,die,78,male,yes,yes,no,yes,yes,yes,yes,yes,yes,yes,yes,0.7,96.0,32.0,4.0,NaN,no
3,die,31,male,NaN,no,yes,yes,yes,yes,yes,yes,yes,yes,yes,0.7,46.0,52.0,4.0,80.0,no
4,die,34,male,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,1.0,NaN,200.0,4.0,NaN,no
5,die,34,male,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,0.9,95.0,28.0,4.0,75.0,no
6,life,51,male,no,yes,no,yes,no,yes,yes,no,no,yes,yes,NaN,NaN,NaN,NaN,NaN,no
7,die,23,male,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,1.0,NaN,NaN,NaN,NaN,no
8,die,39,male,yes,yes,no,yes,yes,yes,no,yes,yes,yes,yes,0.7,NaN,48.0,4.4,NaN,no
9,die,30,male,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,1.0,NaN,120.0,3.9,NaN,no

In [6]:
data.tail(n=10)

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
145,die,31,male,no,yes,no,yes,yes,yes,yes,yes,yes,yes,yes,1.2,75.0,173.0,4.2,54.0,yes
146,life,41,male,yes,yes,no,yes,yes,yes,no,no,no,yes,no,4.2,65.0,120.0,3.4,NaN,yes
147,life,70,male,no,yes,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,1.7,109.0,528.0,2.8,35.0,yes
148,die,20,male,no,yes,yes,yes,yes,yes,NaN,yes,yes,yes,yes,0.9,89.0,152.0,4.0,NaN,yes
149,die,36,male,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,0.6,120.0,30.0,4.0,NaN,yes
150,life,46,male,yes,yes,no,no,no,yes,yes,yes,no,no,no,7.6,NaN,242.0,3.3,50.0,yes
151,die,44,male,yes,yes,no,yes,yes,yes,no,yes,yes,yes,yes,0.9,126.0,142.0,4.3,NaN,yes
152,die,61,male,no,yes,no,no,yes,no,no,yes,no,yes,yes,0.8,75.0,20.0,4.1,NaN,yes
153,die,53,female,no,yes,no,yes,yes,yes,yes,no,no,yes,no,1.5,81.0,19.0,4.1,48.0,yes
154,life,43,male,yes,yes,no,yes,yes,yes,yes,no,no,no,yes,1.2,100.0,19.0,3.1,42.0,yes

In [7]:
#Statistik Deskriptif
data.describe()

              Age   Bilirubin  Alk Phospat       SGOT     Albumin     Protime
count  155.000000  149.000000   126.000000  151.00000  139.000000   88.000000
mean    41.200000    1.427517   105.325397   85.89404    3.817266   61.852273
std     12.565878    1.212149    51.508109   89.65089    0.651523   22.875244
min      7.000000    0.300000    26.000000   14.00000    2.100000    0.000000
25%     32.000000    0.700000    74.250000   31.50000    3.400000   46.000000
50%     39.000000    1.000000    85.000000   58.00000    4.000000   61.000000
75%     50.000000    1.500000   132.250000  100.50000    4.200000   76.250000
max     78.000000    8.000000   295.000000  648.00000    6.400000  100.000000

In [8]:
data['Sex'].value_counts()

male      139
female     16
Name: Sex, dtype: int64

In [10]:
data['Steroid'].value_counts()

yes    78
no     76
Name: Steroid, dtype: int64

In [14]:
data['Liver Big'].value_counts()

yes    120
no      25
Name: Liver Big, dtype: int64

In [15]:
data['Liver Firm'].value_counts()

yes    84
no     60
Name: Liver Firm, dtype: int64

## Imputation Missing Value

In [12]:
#Jumlah data missing value (NA)
np.sum(data.isnull())

Class              0
Age                0
Sex                0
Steroid            1
Antivirals         0
Fatigue            1
Malaise            1
Anaroxia           1
Liver Big         10
Liver Firm        11
Spleen Pabable     5
Spiders            5
Ascites            5
Varices            5
Bilirubin          6
Alk Phospat       29
SGOT               4
Albumin           16
Protime           67
Histology          0
dtype: int64

In [16]:
data.isnull().sum()

Class              0
Age                0
Sex                0
Steroid            1
Antivirals         0
Fatigue            1
Malaise            1
Anaroxia           1
Liver Big         10
Liver Firm        11
Spleen Pabable     5
Spiders            5
Ascites            5
Varices            5
Bilirubin          6
Alk Phospat       29
SGOT               4
Albumin           16
Protime           67
Histology          0
dtype: int64

In [17]:
data.isnull().sum().sum()

167

In [18]:
#Imputasi missing value untuk data numerik
#data numerik di imputasi dengan nilai mean variabel
data['Bilirubin'] = data['Bilirubin'].fillna((data['Bilirubin'].mean())) 
data['Alk Phospat'] = data['Alk Phospat'].fillna((data['Alk Phospat'].mean()))
data['SGOT'] = data['SGOT'].fillna((data['SGOT'].mean()))
data['Albumin'] = data['Albumin'].fillna((data['Albumin'].mean()))
data['Protime'] = data['Protime'].fillna((data['Protime'].mean()))
data.isnull().any()

Class             False
Age               False
Sex               False
Steroid            True
Antivirals        False
Fatigue            True
Malaise            True
Anaroxia           True
Liver Big          True
Liver Firm         True
Spleen Pabable     True
Spiders            True
Ascites            True
Varices            True
Bilirubin         False
Alk Phospat       False
SGOT              False
Albumin           False
Protime           False
Histology         False
dtype: bool

In [21]:
#Imputasi missing value untuk data kategorik
#data kategorik di imputasi dengan nilai modus
data['Liver Big'] = data.fillna(data['Liver Big'].value_counts().index[0])
data['Liver Firm'] = data.fillna(data['Liver Firm'].value_counts().index[0])
data['Spleen Pabable'] = data.fillna(data['Spleen Pabable'].value_counts().index[0])
data['Spiders'] = data.fillna(data['Spiders'].value_counts().index[0])
data['Ascites'] = data.fillna(data['Ascites'].value_counts().index[0])
data['Varices'] = data.fillna(data['Varices'].value_counts().index[0])
data.isnull().any()

Class             False
Age               False
Sex               False
Steroid            True
Antivirals        False
Fatigue            True
Malaise            True
Anaroxia           True
Liver Big         False
Liver Firm        False
Spleen Pabable    False
Spiders           False
Ascites           False
Varices           False
Bilirubin         False
Alk Phospat       False
SGOT              False
Albumin           False
Protime           False
Histology         False
dtype: bool

In [22]:
#Imputasi missing value untuk data kategorik
#data kategorik di imputasi dengan nilai modus variabel
data = data.apply(lambda x:x.fillna(x.value_counts().index[0]))
data.isnull().any()

Class             False
Age               False
Sex               False
Steroid           False
Antivirals        False
Fatigue           False
Malaise           False
Anaroxia          False
Liver Big         False
Liver Firm        False
Spleen Pabable    False
Spiders           False
Ascites           False
Varices           False
Bilirubin         False
Alk Phospat       False
SGOT              False
Albumin           False
Protime           False
Histology         False
dtype: bool

In [23]:
data.head()

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
0,die,30,female,no,yes,yes,yes,yes,die,die,die,die,die,die,1.0,85.000000,18.0,4.0,61.852273,no
1,die,50,male,no,yes,no,yes,yes,die,die,die,die,die,die,0.9,135.000000,42.0,3.5,61.852273,no
2,die,78,male,yes,yes,no,yes,yes,die,die,die,die,die,die,0.7,96.000000,32.0,4.0,61.852273,no
3,die,31,male,yes,no,yes,yes,yes,die,die,die,die,die,die,0.7,46.000000,52.0,4.0,80.000000,no
4,die,34,male,yes,yes,yes,yes,yes,die,die,die,die,die,die,1.0,105.325397,200.0,4.0,61.852273,no

## Encode Labels

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
#Encode untuk data kategorik
data['Class'] = LabelEncoder().fit_transform(data['Class'])
data['Sex'] = LabelEncoder().fit_transform(data['Sex'])
data['Steroid'] = LabelEncoder().fit_transform(data['Steroid'])
data['Antivirals'] = LabelEncoder().fit_transform(data['Antivirals'])
data['Fatigue'] = LabelEncoder().fit_transform(data['Fatigue'])
data['Malaise'] = LabelEncoder().fit_transform(data['Malaise'])
data['Anaroxia'] = LabelEncoder().fit_transform(data['Anaroxia'])
data['Liver Big'] = LabelEncoder().fit_transform(data['Liver Big'])
data['Liver Firm'] = LabelEncoder().fit_transform(data['Liver Firm'])
data['Spleen Pabable'] = LabelEncoder().fit_transform(data['Spleen Pabable'])
data['Spiders'] = LabelEncoder().fit_transform(data['Spiders'])
data['Ascites'] = LabelEncoder().fit_transform(data['Ascites'])
data['Varices'] = LabelEncoder().fit_transform(data['Varices'])
data['Histology'] = LabelEncoder().fit_transform(data['Histology'])
data.head(n=10)

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
0,0,30,0,0,1,1,1,1,0,0,0,0,0,0,1.000000,85.000000,18.00000,4.000000,61.852273,0
1,0,50,1,0,1,0,1,1,0,0,0,0,0,0,0.900000,135.000000,42.00000,3.500000,61.852273,0
2,0,78,1,1,1,0,1,1,0,0,0,0,0,0,0.700000,96.000000,32.00000,4.000000,61.852273,0
3,0,31,1,1,0,1,1,1,0,0,0,0,0,0,0.700000,46.000000,52.00000,4.000000,80.000000,0
4,0,34,1,1,1,1,1,1,0,0,0,0,0,0,1.000000,105.325397,200.00000,4.000000,61.852273,0
5,0,34,1,1,1,1,1,1,0,0,0,0,0,0,0.900000,95.000000,28.00000,4.000000,75.000000,0
6,1,51,1,0,1,0,1,0,1,1,1,1,1,1,1.427517,105.325397,85.89404,3.817266,61.852273,0
7,0,23,1,1,1,1,1,1,0,0,0,0,0,0,1.000000,105.325397,85.89404,3.817266,61.852273,0
8,0,39,1,1,1,0,1,1,0,0,0,0,0,0,0.700000,105.325397,48.00000,4.400000,61.852273,0
9,0,30,1,1,1,1,1,1,0,0,0,0,0,0,1.000000,105.325397,120.00000,3.900000,61.852273,0

# Standardize

In [26]:
#Standardize digunakanan untuk data numerik yang bernilai >0 (positif)
from sklearn.preprocessing import StandardScaler

In [28]:
data['Age'] = StandardScaler().fit(data[['Age']]).transform(data[['Age']])
data['Bilirubin'] = StandardScaler().fit(data[['Bilirubin']]).transform(data[['Bilirubin']])
data['Alk Phospat'] = StandardScaler().fit(data[['Alk Phospat']]).transform(data[['Alk Phospat']])
data['SGOT'] = StandardScaler().fit(data[['SGOT']]).transform(data[['SGOT']])
data['Albumin'] = StandardScaler().fit(data[['Albumin']]).transform(data[['Albumin']])
data['Protime'] = StandardScaler().fit(data[['Protime']]).transform(data[['Protime']])
data

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
0,0,-0.894192,0,0,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-4.394144e-01,-0.769834,2.972456e-01,-4.146013e-16,0
1,0,0.702579,1,0,1,0,1,1,0,0,0,0,0,0,-4.453641e-01,6.415347e-01,-0.497704,-5.160839e-01,-4.146013e-16,0
2,0,2.938059,1,1,1,0,1,1,0,0,0,0,0,0,-6.142172e-01,-2.016056e-01,-0.611092,2.972456e-01,-4.146013e-16,0
3,0,-0.814353,1,1,0,1,1,1,0,0,0,0,0,0,-6.142172e-01,-1.282555e+00,-0.384316,2.972456e-01,1.058919e+00,0
4,0,-0.574838,1,1,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-5.509614e-17,1.293820,2.972456e-01,-4.146013e-16,0
5,0,-0.574838,1,1,1,1,1,1,0,0,0,0,0,0,-4.453641e-01,-2.232246e-01,-0.656447,2.972456e-01,7.671692e-01,0
6,1,0.782418,1,0,1,0,1,0,1,1,1,1,1,1,-3.749291e-16,-5.509614e-17,0.000000,-2.167145e-15,-4.146013e-16,0
7,0,-1.453062,1,1,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-5.509614e-17,0.000000,-2.167145e-15,-4.146013e-16,0
8,0,-0.175645,1,1,1,0,1,1,0,0,0,0,0,0,-6.142172e-01,-5.509614e-17,-0.429671,9.479092e-01,-4.146013e-16,0
9,0,-0.894192,1,1,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-5.509614e-17,0.386719,1.345797e-01,-4.146013e-16,0
10,0,-0.175645,1,0,0,1,1,1,0,0,0,0,0,0,-1.076580e-01,-5.907473e-01,-0.633769,9.479092e-01,1.350669e+00,0
11,0,-0.734515,1,1,0,0,1,1,0,0,0,0,0,0,-3.609376e-01,-1.001508e+00,1.849420,-1.907521e-01,-4.581797e-01,0
12,0,-0.015968,1,1,0,0,1,1,0,0,0,0,0,0,-4.453641e-01,-5.258903e-01,-0.293606,1.345797e-01,-5.748796e-01,0
13,0,-0.894192,1,1,1,0,1,1,0,0,0,0,0,0,6.521808e-01,-1.044746e+00,0.658850,1.761239e+00,9.422191e-01,0
14,0,0.463064,1,0,0,1,1,1,0,0,0,0,0,0,-3.749291e-16,-5.509614e-17,-0.293606,-2.167145e-15,-4.146013e-16,0
15,0,-0.255483,1,0,1,0,0,0,0,0,0,0,0,0,4.833278e-01,-7.204612e-01,0.035218,-1.492079e+00,-9.249793e-01,0
16,0,1.979996,1,1,1,0,1,1,0,0,0,0,0,0,-1.920845e-01,-7.189169e-02,-0.372978,7.852433e-01,-4.146013e-16,0
17,0,-0.095806,1,0,1,0,1,1,0,0,0,0,0,0,-6.986438e-01,-9.366510e-01,0.908302,2.972456e-01,6.696983e-02,0
18,0,-0.255483,1,1,1,1,1,1,0,0,0,0,0,0,-6.142172e-01,-1.131222e+00,-0.497704,4.599115e-01,1.350669e+00,1
19,0,-0.255483,1,0,0,1,1,1,0,0,0,0,0,0,-6.142172e-01,-7.636991e-01,-0.656447,6.225774e-01,8.619879e-03,0
20,0,-1.532900,0,1,0,0,1,1,0,0,0,0,0,0,-4.453641e-01,-1.239317e+00,-0.747157,6.225774e-01,1.253198e-01,0
21,0,-1.133707,1,1,1,0,0,0,0,0,0,0,0,0,-1.920845e-01,5.982967e-01,0.137267,4.599115e-01,-1.333429e+00,0
22,0,-0.814353,1,1,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-4.394144e-01,-0.747157,2.972456e-01,2.225918e+00,0
23,0,0.063871,1,1,1,1,1,1,0,0,0,0,0,0,-4.453641e-01,-9.798889e-01,-0.259590,1.435907e+00,-8.666294e-01,0
24,0,-1.293385,0,0,0,1,1,1,0,0,0,0,0,0,-8.674968e-01,-1.304174e+00,-0.769834,7.852433e-01,4.754195e-01,0
25,0,-1.133707,1,0,1,0,0,1,0,0,0,0,0,0,-5.297907e-01,-2.232246e-01,-0.452349,-2.808620e-02,2.225918e+00,0
26,0,0.622741,1,0,0,0,0,0,0,0,0,0,0,0,-6.986438e-01,-4.394144e-01,-0.429671,-1.907521e-01,-4.146013e-16,0
27,0,1.341288,0,1,1,0,1,1,0,0,0,0,0,0,-2.323146e-02,1.506294e+00,-0.350300,-1.817411e+00,-1.508479e+00,0
28,0,1.580803,1,0,1,0,1,1,0,0,0,0,0,0,-1.076580e-01,-5.907473e-01,-0.690463,-2.808620e-02,2.225918e+00,0
29,0,0.782418,1,0,0,0,0,1,0,0,0,0,0,0,-3.609376e-01,-5.907473e-01,-0.316284,1.273241e+00,-5.748796e-01,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,0,-0.574838,0,1,1,0,0,0,0,0,0,0,0,0,-6.142172e-01,-7.636991e-01,-0.701802,4.599115e-01,2.225918e+00,1
126,0,-1.053869,1,1,1,0,0,0,0,0,0,0,0,0,-3.609376e-01,-5.509614e-17,-0.747157,2.972456e-01,-4.146013e-16,1
127,1,0.702579,1,1,1,0,1,1,1,1,1,1,1,1,1.158740e+00,1.073914e+00,-0.123525,-2.305409e+00,-1.741879e+00,1
128,0,1.021933,1,0,1,0,0,1,0,0,0,0,0,0,-1.920845e-01,-4.394144e-01,0.069234,-1.166747e+00,2.420197e-01,1
129,1,1.261449,1,0,1,0,0,1,1,1,1,1,1,1,2.678418e+00,-5.042713e-01,-0.350300,-8.414157e-01,-1.858579e+00,1
130,0,1.021933,1,1,1,1,1,1,0,0,0,0,0,0,-3.609376e-01,-4.394144e-01,-0.633769,1.110575e+00,-3.609077e+00,1
131,1,-0.814353,1,0,1,0,0,0,1,1,1,1,1,1,5.548920e+00,-5.509614e-17,0.171283,-2.630740e+00,-4.146013e-16,1
132,0,0.542902,1,1,1,0,0,0,0,0,0,0,0,0,4.833278e-01,1.138771e+00,2.178244,-2.808620e-02,-4.146013e-16,1
133,0,2.459027,1,1,0,0,1,1,0,0,0,0,0,0,-3.609376e-01,2.091551e-01,-0.384316,-6.787498e-01,-6.915795e-01,1
134,1,-0.255483,1,0,1,1,1,1,1,1,1,1,1,1,-8.674968e-01,2.976385e+00,-0.418333,-2.808620e-02,1.642418e+00,1
135,0,-1.293385,1,1,1,0,1,1,0,0,0,0,0,0,-1.076580e-01,1.636008e+00,1.078384,1.110575e+00,-2.831299e-01,1
136,0,0.782418,1,1,1,1,1,1,0,0,0,0,0,0,-5.297907e-01,-5.509614e-17,-0.599753,1.110575e+00,-4.146013e-16,1
137,0,-0.255483,1,1,1,1,1,1,0,0,0,0,0,0,1.456216e-01,5.334398e-01,0.613495,-5.160839e-01,-3.414798e-01,1
138,1,0.463064,1,1,1,0,0,1,1,1,1,1,1,1,-3.609376e-01,1.311723e+00,-0.633769,-1.980077e+00,-1.800229e+00,1
139,0,0.303386,1,1,0,1,1,1,0,0,0,0,0,0,-1.076580e-01,-4.394144e-01,-0.475027,6.225774e-01,1.350669e+00,1
140,0,-0.415160,1,0,1,0,0,0,0,0,0,0,0,0,2.300481e-01,4.100572e+00,-0.293606,-1.817411e+00,-4.146013e-16,1
141,1,1.021933,1,0,1,0,0,1,1,1,1,1,1,1,2.087432e+00,3.172500e-01,-0.656447,-5.160839e-01,-1.100029e+00,1
142,0,0.782418,1,1,1,0,1,1,0,0,0,0,0,0,-3.609376e-01,-5.509614e-17,-0.747157,-1.329413e+00,6.696983e-02,1
143,1,0.622741,1,0,1,0,0,1,1,1,1,1,1,1,-2.323146e-02,-4.394144e-01,-0.180219,-5.160839e-01,-1.566829e+00,1
144,1,0.303386,1,1,1,0,0,0,1,1,1,1,1,1,3.989012e-01,-5.509614e-17,0.318687,-2.305409e+00,-4.146013e-16,1
145,0,-0.814353,1,0,1,0,1,1,0,0,0,0,0,0,-1.920845e-01,-6.556042e-01,0.987674,6.225774e-01,-4.581797e-01,1
146,1,-0.015968,1,1,1,0,1,1,1,1,1,1,1,1,2.340712e+00,-8.717940e-01,0.386719,-6.787498e-01,-4.146013e-16,1
147,1,2.299350,1,0,1,0,0,0,1,1,1,1,1,1,2.300481e-01,7.944118e-02,5.012934,-1.654745e+00,-1.566829e+00,1
148,0,-1.692577,1,0,1,1,1,1,0,0,0,0,0,0,-4.453641e-01,-3.529385e-01,0.749560,2.972456e-01,-4.146013e-16,1
149,0,-0.415160,1,1,1,1,1,1,0,0,0,0,0,0,-6.986438e-01,3.172500e-01,-0.633769,2.972456e-01,-4.146013e-16,1
150,1,0.383225,1,1,1,0,0,0,1,1,1,1,1,1,5.211214e+00,-5.509614e-17,1.770048,-8.414157e-01,-6.915795e-01,1
151,0,0.223548,1,1,1,0,1,1,0,0,0,0,0,0,-4.453641e-01,4.469639e-01,0.636172,7.852433e-01,-4.146013e-16,1
152,0,1.580803,1,0,1,0,0,1,0,0,0,0,0,0,-5.297907e-01,-6.556042e-01,-0.747157,4.599115e-01,-4.146013e-16,1
153,0,0.942095,0,0,1,0,1,1,0,0,0,0,0,0,6.119507e-02,-5.258903e-01,-0.758496,4.599115e-01,-8.082794e-01,1
154,1,0.143709,1,1,1,0,1,1,1,1,1,1,1,1,-1.920845e-01,-1.151297e-01,-0.758496,-1.166747e+00,-1.158379e+00,1

## Normalize

In [29]:
#data numerik
from sklearn.preprocessing import Normalizer

In [30]:
data['Age'] = Normalizer().fit(data[['Age']]).transform(data[['Age']])
data['Bilirubin'] = Normalizer().fit(data[['Bilirubin']]).transform(data[['Bilirubin']])
data['Alk Phospat'] = Normalizer().fit(data[['Alk Phospat']]).transform(data[['Alk Phospat']])
data['SGOT'] = Normalizer().fit(data[['SGOT']]).transform(data[['Alk Phospat']])
data['Albumin'] = Normalizer().fit(data[['Albumin']]).transform(data[['Albumin']])
data['Protime'] = Normalizer().fit(data[['Protime']]).transform(data[['Protime']])

In [31]:
data.head(n=10)

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
0,0,-1.0,0,0,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,0
1,0,1.0,1,0,1,0,1,1,0,0,0,0,0,0,-1.0,1.0,1.0,-1.0,-1.0,0
2,0,1.0,1,1,1,0,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,0
3,0,-1.0,1,1,0,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,1.0,0
4,0,-1.0,1,1,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,0
5,0,-1.0,1,1,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,1.0,0
6,1,1.0,1,0,1,0,1,0,1,1,1,1,1,1,-1.0,-1.0,-1.0,-1.0,-1.0,0
7,0,-1.0,1,1,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,-1.0,-1.0,0
8,0,-1.0,1,1,1,0,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,0
9,0,-1.0,1,1,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,0

In [32]:
data.tail(n=10)

,Class,Age,Sex,Steroid,Antivirals,Fatigue,Malaise,Anaroxia,Liver Big,Liver Firm,Spleen Pabable,Spiders,Ascites,Varices,Bilirubin,Alk Phospat,SGOT,Albumin,Protime,Histology
145,0,-1.0,1,0,1,0,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,1
146,1,-1.0,1,1,1,0,1,1,1,1,1,1,1,1,1.0,-1.0,-1.0,-1.0,-1.0,1
147,1,1.0,1,0,1,0,0,0,1,1,1,1,1,1,1.0,1.0,1.0,-1.0,-1.0,1
148,0,-1.0,1,0,1,1,1,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,1
149,0,-1.0,1,1,1,1,1,1,0,0,0,0,0,0,-1.0,1.0,1.0,1.0,-1.0,1
150,1,1.0,1,1,1,0,0,0,1,1,1,1,1,1,1.0,-1.0,-1.0,-1.0,-1.0,1
151,0,1.0,1,1,1,0,1,1,0,0,0,0,0,0,-1.0,1.0,1.0,1.0,-1.0,1
152,0,1.0,1,0,1,0,0,1,0,0,0,0,0,0,-1.0,-1.0,-1.0,1.0,-1.0,1
153,0,1.0,0,0,1,0,1,1,0,0,0,0,0,0,1.0,-1.0,-1.0,1.0,-1.0,1
154,1,1.0,1,1,1,0,1,1,1,1,1,1,1,1,-1.0,-1.0,-1.0,-1.0,-1.0,1